title: Shuo Lei
position: Ph.D. Candidate
affiliation: Virginia Tech
email: slei (at) vt.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=vm368LkAAAAJ&hl=en
github_link: https://github.com/slei109
linkedin: https://www.linkedin.com/
avatar: ./assets/img/Shuo.jpg
#google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
#canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
